// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEX9Eiw7LoQfDLd4ByzzJM8Wovgl_L2CE',
    appId: '1:264034719694:web:0ce844afac0e31de7b3d9f',
    messagingSenderId: '264034719694',
    projectId: 'raf1app',
    authDomain: 'raf1app.firebaseapp.com',
    storageBucket: 'raf1app.appspot.com',
    measurementId: 'G-0NYRKJEJL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNBBzkKRz6YrkZWLR3xkFEfYYSEKTII50',
    appId: '1:264034719694:android:c01d861121da95607b3d9f',
    messagingSenderId: '264034719694',
    projectId: 'raf1app',
    storageBucket: 'raf1app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzsBzmKbC_u9Kydt_Sf6SZaHHmpO6SAus',
    appId: '1:264034719694:ios:082ccbfa427099337b3d9f',
    messagingSenderId: '264034719694',
    projectId: 'raf1app',
    storageBucket: 'raf1app.appspot.com',
    iosClientId: '264034719694-ij9bjc1vllkg3pap2ujv6ojpv0k07roh.apps.googleusercontent.com',
    iosBundleId: 'com.genius.raf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzsBzmKbC_u9Kydt_Sf6SZaHHmpO6SAus',
    appId: '1:264034719694:ios:25ff5919139d84477b3d9f',
    messagingSenderId: '264034719694',
    projectId: 'raf1app',
    storageBucket: 'raf1app.appspot.com',
    iosClientId: '264034719694-3t9pqv8f52vp2v67v48o9j6k7u4pnjr6.apps.googleusercontent.com',
    iosBundleId: 'com.genius.raf.RunnerTests',
  );
}
